### ISSUE TITLE
MC_ENCHANT error

### ISSUE THREAD

**Issue by mithyldr** [Dasffion/Mastercraft#1]
What am I doing wrong? 
[Script error in mc_enchant.cmd, mc_include.cmd(23): Eval (replacere("silversteel mallet|glaes-edged shovel|muracite tongs|hooked pliers|leather bellows|stirring rod|iron chisel|bone saw|iron rasp|square riffler|tools|carving knife|wood shaper|metal drawknife|metal clamps|sewing needles|ka'hurst scissors|slickstone|silversteel yardstick|uthamar awl|purpleheart bowl|stone mortar|mixing stick|belzune pestle|wirework sieve|burin|loop", "\|$", "")) contains variable character '$'. Did you use an unassigned variable?]

Thank you!

**Comment by Dasffion** [comment]
Doing nothing wrong. A script error as reported by Genie isn't necessarily an actual script error. In this case it's seeing "$" that is used as regex and thinks that it could be an unassigned variable
